# ons_loader.py
from __future__ import annotations

"""
Helpers for pulling ONS / Nomis earnings data (ASHE) via the REST API.

This module is deliberately lightweight:

- Reads your Nomis Unique ID from the NOMIS_UID env var.
- Fetches Annual Survey of Hours and Earnings (ASHE) data for a single year.
- Returns a list of parsed rows ready to be stored / joined in the app.

At the moment this DOES NOT write to the database. The function
`import_ons_earnings_for_year()` just downloads + parses and returns
a summary dict so we can iterate on the schema safely.

Once you're happy with the dataset & structure, we can add a simple
OnsEarnings model and store these rows for fast joins in the UI.
"""

import csv
import io
import os
from dataclasses import dataclass
from datetime import date
from typing import List, Dict, Any, Optional

import requests
from dotenv import load_dotenv

load_dotenv()

# -------------------------------------------------------------------
# Configuration
# -------------------------------------------------------------------

BASE_URL = "https://www.nomisweb.co.uk/api/v01"

# Your Nomis Unique ID (from the page you screenshotted)
# e.g. NOMIS_UID=0x2ebb06d0df0f3107c4cc4ea8211320cc306e94b
NOMIS_UID = os.getenv("NOMIS_UID")

# ------------------- IMPORTANT: DATASET CHOICES --------------------
# Nomis has multiple ASHE datasets (workplace/residence, full/part-time etc).
# Rather than hard-coding one, we make it configurable so you can point it
# at exactly the query you build in the Nomis UI.
#
# Recommended approach:
# 1) Use the Nomis web UI to build the query you want
#    (ASHE earnings, "All employees", median gross hourly pay,
#     geography = local authority / county).
# 2) On the final "Format" page, choose "CSV" and copy the RESTful link.
# 3) Take the dataset id (NM_xxx_x) and the key query parameters from that link
#    and plug them into the constants below.
#
# Until you configure these, calls will raise a ValueError explaining what to set.

ASHE_DATASET_ID = os.getenv("NOMIS_ASHE_DATASET_ID")  # e.g. "NM_99_1"

# Geography dimension:
#   TYPE450 = Local authorities: County / Unitary (for England/Wales)
ASHE_GEOGRAPHY = os.getenv("NOMIS_ASHE_GEOGRAPHY")  # e.g. "TYPE450"

# Measures:
#   20101 = Median gross hourly pay (excluding overtime)
ASHE_MEASURES = os.getenv("NOMIS_ASHE_MEASURES")  # e.g. "20101"

# Sex / full-time / occupation etc can also be constrained.
# Copy these straight from the Nomis URL.
ASHE_EXTRA_PARAMS = os.getenv("NOMIS_ASHE_EXTRA_PARAMS", "").strip()
# Example:
#   NOMIS_ASHE_EXTRA_PARAMS="sex=0&item=1&pay=5&freq=A"
# These get appended to the query string as-is.

# Some datasets use TIME, others DATE as the dimension id.
# NM_99_1 uses DATE in the query string, even though the concept is TIME.
ASHE_DATE_PARAM = os.getenv("NOMIS_ASHE_DATE_PARAM", "date")  # <-- KEY BIT


# -------------------------------------------------------------------
# Types
# -------------------------------------------------------------------

@dataclass
class OnsEarningsRow:
    year: int
    geography_code: str
    geography_name: str
    measure_code: str
    value: Optional[float]

    def as_dict(self) -> Dict[str, Any]:
        return {
            "year": self.year,
            "geography_code": self.geography_code,
            "geography_name": self.geography_name,
            "measure_code": self.measure_code,
            "value": self.value,
        }


# -------------------------------------------------------------------
# Low-level HTTP helper
# -------------------------------------------------------------------

def _nomis_get_csv(dataset_id: str, params: Dict[str, Any]) -> str:
    """
    Fetch raw CSV from a Nomis dataset.

    `dataset_id` is something like "NM_99_1".
    `params` is the querystring dict (geography, time/date, measures, etc).
    """
    if not dataset_id:
        raise ValueError(
            "ASHE_DATASET_ID / NOMIS_ASHE_DATASET_ID is not set. "
            "Configure it based on the REST link generated by Nomis."
        )

    url = f"{BASE_URL}/dataset/{dataset_id}.data.csv"

    # Inject UID if available
    if NOMIS_UID:
        params = dict(params)
        params["uid"] = NOMIS_UID

    resp = requests.get(url, params=params, timeout=30)
    try:
        resp.raise_for_status()
    except Exception as e:  # noqa: BLE001
        # Bubble up a clearer error message including the final URL
        raise RuntimeError(
            f"Nomis request failed: {e!r} | URL={resp.url} | status={resp.status_code}"
        ) from e

    return resp.text


# -------------------------------------------------------------------
# High-level ASHE earnings importer
# -------------------------------------------------------------------

def _ensure_config():
    """Simple guard to make sure you've wired the environment vars."""
    missing = []
    if not ASHE_DATASET_ID:
        missing.append("NOMIS_ASHE_DATASET_ID (e.g. NM_99_1)")
    if not ASHE_GEOGRAPHY:
        missing.append("NOMIS_ASHE_GEOGRAPHY (e.g. TYPE450)")
    if not ASHE_MEASURES:
        missing.append("NOMIS_ASHE_MEASURES (e.g. 20101 for median hourly)")

    if missing:
        raise ValueError(
            "ONS / Nomis ASHE config is incomplete. Please set:\n- "
            + "\n- ".join(missing)
            + "\n\nUse the Nomis UI to build your ASHE query, "
              "copy the RESTful link, and copy the dataset + parameter values "
              "into these environment variables."
        )


def import_ons_earnings_for_year(year: int) -> Dict[str, Any]:
    """
    Fetch ASHE earnings for a single year from Nomis.

    Returns a summary dict:

      {
        "year": 2024,
        "dataset_id": "...",
        "measure_code": "...",
        "row_count": 152,
        "rows": [OnsEarningsRow.as_dict(), ...],
      }
    """
    _ensure_config()

    # Build core params for the CSV call.
    # IMPORTANT: use DATE (not TIME) for NM_99_1.
    params: Dict[str, Any] = {
        ASHE_DATE_PARAM: str(year),        # <-- HERE: 'date': '2025'
        "geography": ASHE_GEOGRAPHY,
        "measures": ASHE_MEASURES,
        # Only pull what we need — names + codes + value.
        "select": "geography_code,geography_name,measures,obs_value",
        # One row per geography x measure.
        "rows": "geography",
        "cols": "measures",
    }

    # Allow you to tack on extra params straight from your Nomis URL,
    # e.g. "sex=0&item=1&pay=5&freq=A".
    if ASHE_EXTRA_PARAMS:
        for part in ASHE_EXTRA_PARAMS.split("&"):
            part = part.strip()
            if not part or "=" not in part:
                continue
            k, v = part.split("=", 1)
            if k and k not in params:
                params[k] = v

    csv_text = _nomis_get_csv(ASHE_DATASET_ID, params)

    # Parse CSV
    f = io.StringIO(csv_text)
    reader = csv.DictReader(f)

    rows: List[OnsEarningsRow] = []
    for raw in reader:
        # Nomis column names are typically upper-case: GEOGRAPHY_CODE, OBS_VALUE, etc.
        geo_code = (raw.get("GEOGRAPHY_CODE") or "").strip()
        geo_name = (raw.get("GEOGRAPHY_NAME") or "").strip()
        measure = (raw.get("MEASURES") or raw.get("MEASURES_NAME") or "").strip()
        val_raw = (raw.get("OBS_VALUE") or "").strip()

        if not geo_code and not geo_name:
            # Header / blank line / rubbish
            continue

        try:
            value = float(val_raw) if val_raw not in ("", ".", ":", None) else None
        except ValueError:
            value = None

        rows.append(
            OnsEarningsRow(
                year=year,
                geography_code=geo_code,
                geography_name=geo_name,
                measure_code=measure,
                value=value,
            )
        )

    summary = {
        "year": year,
        "dataset_id": ASHE_DATASET_ID,
        "measure_code": ASHE_MEASURES,
        "row_count": len(rows),
        "rows": [r.as_dict() for r in rows],
        "fetched_at": date.today().isoformat(),
    }

    print(
        f"[ONS] Imported ASHE earnings for {year}: "
        f"{summary['row_count']} rows from dataset {ASHE_DATASET_ID}"
    )

    return summary
