# ons_loader.py
from __future__ import annotations

"""
Helpers for pulling ONS / Nomis earnings data (ASHE) via the REST API.

This module is deliberately lightweight:

- Reads your Nomis Unique ID from the NOMIS_UID env var.
- Fetches Annual Survey of Hours and Earnings (ASHE) data for a single year.
- Returns a list of parsed rows ready to be stored / joined in the app.

At the moment this DOES NOT write to the database. The function
`import_ons_earnings_for_year()` just downloads + parses and returns
a summary dict so we can iterate on the schema safely.

Once you're happy with the dataset & structure, we can add a simple
OnsEarnings model and store these rows for fast joins in the UI.
"""
import csv
import io
import os
from dataclasses import dataclass
from datetime import date
from typing import List, Dict, Any, Optional

import requests
from dotenv import load_dotenv  # <-- add this

load_dotenv()  # <-- now this works

# -------------------------------------------------------------------
# Configuration
# -------------------------------------------------------------------

BASE_URL = "https://www.nomisweb.co.uk/api/v01"

# Your Nomis Unique ID (from the page you screenshotted)
# e.g. NOMIS_UID=0x2ebb06d0df0f3107c4cc4ea8211320cc306e94b
NOMIS_UID = os.getenv("NOMIS_UID")

# ------------------- IMPORTANT: DATASET CHOICES --------------------
# Nomis has multiple ASHE datasets (workplace/residence, full/part-time etc).
# Rather than hard-coding one, we make it configurable so you can point it
# at exactly the query you build in the Nomis UI.
#
# Recommended approach:
# 1) Use the Nomis web UI to build the query you want
#    (ASHE earnings, "All employees", median gross hourly pay,
#     geography = local authority / county).
# 2) On the final "Format" page, choose "CSV" and copy the RESTful link.
# 3) Take the dataset id (NM_xxx_x) and the key query parameters from that link
#    and plug them into the constants below.
#
# Until you configure these, calls will raise a ValueError explaining what to set.

ASHE_DATASET_ID = os.getenv("NOMIS_ASHE_DATASET_ID")  # e.g. "NM_17_5"

# Geography:
# Typical choices (you'll see these in the link Nomis gives you):
#   TYPE450 = Local authorities: County / Unitary (for England/Wales)
#   TYPE480 = Countries / English regions
ASHE_GEOGRAPHY = os.getenv("NOMIS_ASHE_GEOGRAPHY")  # e.g. "TYPE450"

# Measures:
# In ASHE, "measures" usually include:
#   20101 = Median gross hourly pay (excluding overtime)
# Again, copy this from the Nomis link you generate.
ASHE_MEASURES = os.getenv("NOMIS_ASHE_MEASURES")  # e.g. "20101"

# Sex / full-time / occupation etc can also be constrained.
# For now we keep this simple and let you copy the key filters from the Nomis URL.
ASHE_EXTRA_PARAMS = os.getenv("NOMIS_ASHE_EXTRA_PARAMS", "").strip()
# Example:
#   NOMIS_ASHE_EXTRA_PARAMS="sex=0&fulltime=0&occupation=0"
# These get appended to the query string as-is.


# -------------------------------------------------------------------
# Types
# -------------------------------------------------------------------

@dataclass
class OnsEarningsRow:
    year: int
    geography_code: str
    geography_name: str
    measure_code: str
    value: Optional[float]

    def as_dict(self) -> Dict[str, Any]:
        return {
            "year": self.year,
            "geography_code": self.geography_code,
            "geography_name": self.geography_name,
            "measure_code": self.measure_code,
            "value": self.value,
        }


# -------------------------------------------------------------------
# Low-level HTTP helper
# -------------------------------------------------------------------

def _nomis_get_csv(dataset_id: str, params: Dict[str, Any]) -> str:
    """
    Fetch raw CSV from a Nomis dataset.

    `dataset_id` is something like "NM_17_5".
    `params` is the querystring dict (geography, time, measures, etc).
    """
    if not dataset_id:
        raise ValueError(
            "ASHE_DATASET_ID / NOMIS_ASHE_DATASET_ID is not set. "
            "Configure it based on the REST link generated by Nomis."
        )

    url = f"{BASE_URL}/dataset/{dataset_id}.data.csv"

    # Inject UID if available
    if NOMIS_UID:
        params = dict(params)
        params["uid"] = NOMIS_UID

    resp = requests.get(url, params=params, timeout=30)
    try:
        resp.raise_for_status()
    except Exception as e:  # noqa: BLE001
        # Bubble up a clearer error message including the final URL
        raise RuntimeError(
            f"Nomis request failed: {e!r} | URL={resp.url} | status={resp.status_code}"
        ) from e

    return resp.text


# -------------------------------------------------------------------
# High-level ASHE earnings importer
# -------------------------------------------------------------------

def _ensure_config():
    """Simple guard to make sure you've wired the environment vars."""
    missing = []
    if not ASHE_DATASET_ID:
        missing.append("NOMIS_ASHE_DATASET_ID (e.g. NM_17_5)")
    if not ASHE_GEOGRAPHY:
        missing.append("NOMIS_ASHE_GEOGRAPHY (e.g. TYPE450)")
    if not ASHE_MEASURES:
        missing.append("NOMIS_ASHE_MEASURES (e.g. 20101 for median hourly)")

    if missing:
        raise ValueError(
            "ONS / Nomis ASHE config is incomplete. Please set:\n- "
            + "\n- ".join(missing)
            + "\n\nUse the Nomis UI to build your ASHE query, "
              "copy the RESTful link, and copy the dataset + parameter values "
              "into these environment variables."
        )

def import_ons_earnings_for_year(year: int) -> Dict[str, Any]:
    """
    Fetch ASHE earnings for a single year from Nomis.

    Returns a summary dict:

      {
        "year": 2024,
        "dataset_id": "...",
        "measure_code": "...",
        "row_count": 152,
        "rows": [OnsEarningsRow.as_dict(), ...],
      }

    At this stage we ONLY download + parse. We do NOT persist to the DB.
    """
    _ensure_config()

    # Build core params for the CSV call.
    # For NM_99_1 the dimension is "date", not "time", so we use date=YYYY.
    params: Dict[str, Any] = {
        "date": str(year),
        "geography": ASHE_GEOGRAPHY,
        "measures": ASHE_MEASURES,
    }

    # Allow you to tack on extra params straight from your Nomis URL,
    # e.g. "sex=1...9&item=1...15&pay=5".
    if ASHE_EXTRA_PARAMS:
        for part in ASHE_EXTRA_PARAMS.split("&"):
            part = part.strip()
            if not part or "=" not in part:
                continue
            k, v = part.split("=", 1)
            # Don't overwrite the core ones we just set
            if k and k not in params:
                params[k] = v

    csv_text = _nomis_get_csv(ASHE_DATASET_ID, params)

    # Parse CSV
    f = io.StringIO(csv_text)
    reader = csv.DictReader(f)

    # ---- NEW: dynamic column detection ----
    fieldnames = reader.fieldnames or []
    upper_map = {name.upper(): name for name in fieldnames}

    def pick_column(*candidates: str, contains: Optional[list[str]] = None) -> Optional[str]:
        # 1) exact candidate matches (case-insensitive)
        for cand in candidates:
            key = upper_map.get(cand.upper())
            if key:
                return key
        # 2) fuzzy "contains" match on uppercased names
        if contains:
            for up, orig in upper_map.items():
                if all(part.upper() in up for part in contains):
                    return orig
        return None

    geo_code_col = pick_column("GEOGRAPHY_CODE", "GEOGCD", "GEOGRAPHY", contains=["GEOG", "CODE"])
    geo_name_col = pick_column("GEOGRAPHY_NAME", "GEOGNM", contains=["GEOG", "NAME"])
    measure_col  = pick_column("MEASURES", "MEASURE_CODE", "ITEM", contains=["MEAS", "ITEM"])
    value_col    = pick_column("OBS_VALUE", "OBS_VALUE_1", "OBS_VALUE_0", "VALUE", contains=["OBS", "VAL"])

    if not value_col:
        # If we can't even find a value column, dump the header to help debugging
        print("[ONS] Could not detect OBS/VALUE column. Headers were:", fieldnames)
        return {
            "year": year,
            "dataset_id": ASHE_DATASET_ID,
            "measure_code": ASHE_MEASURES,
            "row_count": 0,
            "rows": [],
            "fetched_at": date.today().isoformat(),
        }

    rows: List[OnsEarningsRow] = []

    for raw in reader:
        geo_code = (raw.get(geo_code_col) or "").strip() if geo_code_col else ""
        geo_name = (raw.get(geo_name_col) or "").strip() if geo_name_col else ""
        measure  = (raw.get(measure_col)  or "").strip() if measure_col  else ""
        val_raw  = (raw.get(value_col)    or "").strip()

        # Skip pure blank lines
        if not geo_code and not geo_name and not val_raw:
            continue

        try:
            value = float(val_raw) if val_raw not in ("", ".", ":", None) else None
        except ValueError:
            value = None

        rows.append(
            OnsEarningsRow(
                year=year,
                geography_code=geo_code or "",
                geography_name=geo_name or "",
                measure_code=measure or ASHE_MEASURES,
                value=value,
            )
        )

    summary = {
        "year": year,
        "dataset_id": ASHE_DATASET_ID,
        "measure_code": ASHE_MEASURES,
        "row_count": len(rows),
        "rows": [r.as_dict() for r in rows],
        "fetched_at": date.today().isoformat(),
    }

    print(
        f"[ONS] Imported ASHE earnings for {year}: "
        f"{summary['row_count']} rows from dataset {ASHE_DATASET_ID}"
    )

    # If we still somehow got zero rows, print the first few lines of the CSV
    # to help diagnose (doesn't spam too much).
    if summary["row_count"] == 0:
        snippet = "\n".join(csv_text.splitlines()[:10])
        print("[ONS] DEBUG – CSV head (first 10 lines):")
        print(snippet)

    return summary


