# ons_loader.py
from __future__ import annotations

"""
Helpers for pulling ONS / Nomis earnings data (ASHE) via the REST API.

This module is wired to the NM_99_1 dataset using the same parameters
as your working CSV link, then filters down to:

- A single year (requested year if available, otherwise latest)
- Sex = "Total"
- Item = "Median"
- Pay = "Hourly pay - gross"
- Measures = "20100" (Value, not Confidence)

The function `import_ons_earnings_for_year(year)` returns a summary
dict with a list of these rows; ons_importer.py handles DB upsert.
"""

import csv
import io
import os
from dataclasses import dataclass
from datetime import date
from typing import List, Dict, Any, Optional

import requests
from dotenv import load_dotenv

load_dotenv()

# -------------------------------------------------------------------
# Configuration
# -------------------------------------------------------------------

BASE_URL = "https://www.nomisweb.co.uk/api/v01"

# Your Nomis Unique ID (from the Nomis account page)
# e.g. NOMIS_UID=0x2ebb06d0df0f3107c4cc4ea8211320cc306e94b
NOMIS_UID = os.getenv("NOMIS_UID")

# Dataset ID – from your URL this is NM_99_1
ASHE_DATASET_ID = os.getenv("NOMIS_ASHE_DATASET_ID", "NM_99_1")

# Geography – the huge list from your URL, stored in an env var
# NOMIS_ASHE_GEOGRAPHY="1774190644,1774190725,...,1774190606"
ASHE_GEOGRAPHY = os.getenv("NOMIS_ASHE_GEOGRAPHY")

# Measures – from your URL: 20100 (Value) and 20701 (Confidence)
# We will later filter to MEASURES="20100" only.
ASHE_MEASURES = os.getenv("NOMIS_ASHE_MEASURES", "20100,20701")

# Extra params straight from your URL, without geography / measures / date:
#   sex=1...9&item=1...15&pay=5
ASHE_EXTRA_PARAMS = os.getenv(
    "NOMIS_ASHE_EXTRA_PARAMS",
    "sex=1...9&item=1...15&pay=5",
).strip()

# The time dimension parameter name – your URL uses "date"
ASHE_DATE_PARAM = os.getenv("NOMIS_ASHE_DATE_PARAM", "date")

# Date range expression – from your URL: latestMINUS3-latest
ASHE_DATE_RANGE = os.getenv("NOMIS_ASHE_DATE_RANGE", "latestMINUS3-latest")

# Target filters inside the dataset
TARGET_ITEM_NAME = os.getenv("NOMIS_TARGET_ITEM_NAME", "Median")
TARGET_SEX_NAME = os.getenv("NOMIS_TARGET_SEX_NAME", "Total")
TARGET_PAY_NAME = os.getenv("NOMIS_TARGET_PAY_NAME", "Hourly pay - gross")
TARGET_VALUE_MEASURE = os.getenv("NOMIS_TARGET_VALUE_MEASURE", "20100")


# -------------------------------------------------------------------
# Types
# -------------------------------------------------------------------

@dataclass
class OnsEarningsRow:
    year: int
    geography_code: str
    geography_name: str
    measure_code: str
    value: Optional[float]

    def as_dict(self) -> Dict[str, Any]:
        return {
            "year": self.year,
            "geography_code": self.geography_code,
            "geography_name": self.geography_name,
            "measure_code": self.measure_code,
            "value": self.value,
        }


# -------------------------------------------------------------------
# Low-level HTTP helper
# -------------------------------------------------------------------

def _nomis_get_csv(dataset_id: str, params: Dict[str, Any]) -> str:
    """
    Fetch raw CSV from a Nomis dataset.

    `dataset_id` is something like "NM_99_1".
    `params` is the querystring dict (geography, date, measures, etc).
    """
    if not dataset_id:
        raise ValueError(
            "ASHE_DATASET_ID / NOMIS_ASHE_DATASET_ID is not set. "
            "Configure it based on the REST link generated by Nomis."
        )

    url = f"{BASE_URL}/dataset/{dataset_id}.data.csv"

    # Inject UID if available
    if NOMIS_UID:
        params = dict(params)
        params["uid"] = NOMIS_UID

    resp = requests.get(url, params=params, timeout=60)

    try:
        resp.raise_for_status()
    except Exception as e:  # noqa: BLE001
        raise RuntimeError(
            f"Nomis request failed: {e!r} for dataset '{dataset_id}' "
            f"with params {params}. "
            f"This often means the dataset id or parameter combination "
            f"is not valid. | URL={resp.url} | status={resp.status_code}"
        ) from e

    return resp.text


# -------------------------------------------------------------------
# High-level ASHE earnings importer
# -------------------------------------------------------------------

def _ensure_config():
    """Simple guard to make sure you've wired the environment vars."""
    missing = []
    if not ASHE_DATASET_ID:
        missing.append("NOMIS_ASHE_DATASET_ID (e.g. NM_99_1)")
    if not ASHE_GEOGRAPHY:
        missing.append("NOMIS_ASHE_GEOGRAPHY (huge geography list from your URL)")
    if not ASHE_MEASURES:
        missing.append("NOMIS_ASHE_MEASURES (e.g. 20100,20701)")

    if missing:
        raise ValueError(
            "ONS / Nomis ASHE config is incomplete. Please set:\n- "
            + "\n- ".join(missing)
            + "\n\nUse the Nomis UI to build your ASHE query, "
              "copy the RESTful link, and copy the dataset + parameter values "
              "into these environment variables."
        )


def import_ons_earnings_for_year(year: int) -> Dict[str, Any]:
    """
    Fetch ASHE earnings for a single *logical* year.

    Behaviour:

    - Always queries NM_99_1 with:
        date=latestMINUS3-latest
        geography=<your big list>
        measures=20100,20701
        sex=1...9
        item=1...15
        pay=5
    - Parses the CSV.
    - Finds all distinct years present in the DATE column.
    - If `year` is present, we use that.
      Otherwise we fall back to the latest year available.
    - Then we filter to rows where:
        DATE == effective_year
        SEX_NAME == "Total"
        PAY_NAME == "Hourly pay - gross"
        ITEM_NAME == "Median"
        MEASURES == "20100"
    - Returns those rows as OnsEarningsRow dicts.

    The returned `summary["year"]` is the *effective* year actually used.
    """
    _ensure_config()

    # Build params following your working URL structure
    params: Dict[str, Any] = {
        ASHE_DATE_PARAM: ASHE_DATE_RANGE,  # e.g. "date": "latestMINUS3-latest"
        "geography": ASHE_GEOGRAPHY,
        "measures": ASHE_MEASURES,
    }

    # Extra params from NOMIS_ASHE_EXTRA_PARAMS, e.g. "sex=1...9&item=1...15&pay=5"
    if ASHE_EXTRA_PARAMS:
        for part in ASHE_EXTRA_PARAMS.split("&"):
            part = part.strip()
            if not part or "=" not in part:
                continue
            k, v = part.split("=", 1)
            if k and k not in params:
                params[k] = v

    csv_text = _nomis_get_csv(ASHE_DATASET_ID, params)

    # Tiny debug aid: show the first non-empty line
    first_line = next((ln for ln in csv_text.splitlines() if ln.strip()), "")
    print(f"[ONS] Raw CSV first line: {first_line[:200]}")

    f = io.StringIO(csv_text)
    reader = csv.DictReader(f)

    all_rows: List[Dict[str, Any]] = list(reader)
    if not all_rows:
        print(
            f"[ONS] WARNING: 0 raw rows returned for params {params}. "
            f"Nothing to import."
        )
        return {
            "year": year,
            "dataset_id": ASHE_DATASET_ID,
            "measure_code": TARGET_VALUE_MEASURE,
            "row_count": 0,
            "rows": [],
            "fetched_at": date.today().isoformat(),
            "available_years": [],
        }

    # Determine which years exist in the data
    raw_years = sorted({
        (row.get("DATE") or "").strip()
        for row in all_rows
        if (row.get("DATE") or "").strip()
    })
    available_years = [int(y) for y in raw_years if y.isdigit()]

    print(f"[ONS] Available ASHE years in response: {available_years}")

    target_year_str = str(year)
    if available_years and year in available_years:
        effective_year = year
    elif available_years:
        effective_year = max(available_years)
        print(
            f"[ONS] Requested year {year} not in dataset; "
            f"falling back to latest available year {effective_year}."
        )
    else:
        # No parsable years at all; bail out
        print("[ONS] No parsable DATE values found in CSV.")
        return {
            "year": year,
            "dataset_id": ASHE_DATASET_ID,
            "measure_code": TARGET_VALUE_MEASURE,
            "row_count": 0,
            "rows": [],
            "fetched_at": date.today().isoformat(),
            "available_years": [],
        }

    effective_year_str = str(effective_year)

    # Filter rows down to the specific combination we care about
    filtered: List[OnsEarningsRow] = []

    for raw in all_rows:
        if (raw.get("DATE") or "").strip() != effective_year_str:
            continue

        if (raw.get("MEASURES") or "").strip() != TARGET_VALUE_MEASURE:
            continue

        if (raw.get("PAY_NAME") or "").strip() != TARGET_PAY_NAME:
            continue

        if (raw.get("ITEM_NAME") or "").strip() != TARGET_ITEM_NAME:
            continue

        if (raw.get("SEX_NAME") or "").strip() != TARGET_SEX_NAME:
            continue

        geo_code = (raw.get("GEOGRAPHY_CODE") or "").strip()
        geo_name = (raw.get("GEOGRAPHY_NAME") or "").strip()
        val_raw = (raw.get("OBS_VALUE") or "").strip()

        if not geo_code and not geo_name:
            continue

        try:
            value = float(val_raw) if val_raw not in ("", ".", ":", None) else None
        except ValueError:
            value = None

        filtered.append(
            OnsEarningsRow(
                year=effective_year,
                geography_code=geo_code,
                geography_name=geo_name,
                measure_code=TARGET_VALUE_MEASURE,
                value=value,
            )
        )

    summary = {
        "year": effective_year,  # actual dataset year used
        "dataset_id": ASHE_DATASET_ID,
        "measure_code": TARGET_VALUE_MEASURE,
        "row_count": len(filtered),
        "rows": [r.as_dict() for r in filtered],
        "fetched_at": date.today().isoformat(),
        "available_years": available_years,
    }

    print(
        f"[ONS] Imported ASHE (NM_99_1) for {effective_year}: "
        f"{summary['row_count']} rows (requested {year}) "
        f"for {TARGET_SEX_NAME} / {TARGET_PAY_NAME} / {TARGET_ITEM_NAME} "
        f"measure={TARGET_VALUE_MEASURE}"
    )

    if summary["row_count"] == 0:
        print(
            "[ONS] WARNING: 0 filtered rows after applying "
            f"SEX_NAME={TARGET_SEX_NAME!r}, PAY_NAME={TARGET_PAY_NAME!r}, "
            f"ITEM_NAME={TARGET_ITEM_NAME!r}, MEASURES={TARGET_VALUE_MEASURE!r}. "
            "Check that these match the values in the CSV."
        )

    return summary



