"""Add job search role and location fields

Revision ID: 12321e154c34
Revises: edeada651488
Create Date: 2025-11-18 20:24:24.873170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12321e154c34'
down_revision = 'edeada651488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('search_role', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('search_location', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_column('search_location')
        batch_op.drop_column('search_role')

    # ### end Alembic commands ###
