"""add job_role_group to job_record

Revision ID: 1678b54efd38
Revises: abadb4e9bd6d
Create Date: 2025-11-27 15:45:50.771839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1678b54efd38'
down_revision = 'abadb4e9bd6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_role_group', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_job_record_job_role_group'), ['job_role_group'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_record_job_role_group'))
        batch_op.drop_column('job_role_group')

    # ### end Alembic commands ###
