"""Add organisations and org link to users

Revision ID: 1d357c432682
Revises: 9c8dc5073015
Create Date: 2025-12-10 15:59:52.141804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d357c432682'
down_revision = '9c8dc5073015'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'organisations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('slug', sa.String(length=255), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        sa.UniqueConstraint('slug'),
    )

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'org_role',
                sa.String(length=20),
                nullable=False,
                server_default='owner',  # <-- default for existing users
            )
        )
        batch_op.add_column(sa.Column('organisation_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            None,
            'organisations',
            ['organisation_id'],
            ['id'],
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('organisation_id')
        batch_op.drop_column('org_role')

    op.drop_table('organisations')
    # ### end Alembic commands ###
