"""Widen weekly_market_changes.delta_percent

Revision ID: 3abccda5b897
Revises: 913137500a6f
Create Date: 2025-12-21 23:34:51.371881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3abccda5b897'
down_revision = '913137500a6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_market_changes', schema=None) as batch_op:
        batch_op.alter_column('delta_percent',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_market_changes', schema=None) as batch_op:
        batch_op.alter_column('delta_percent',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###
