"""Add job import fields

Revision ID: 3dc050cca740
Revises: 12321e154c34
Create Date: 2025-11-19 10:38:23.452491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dc050cca740'
down_revision = '12321e154c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imported', sa.Boolean(), nullable=True))

    with op.batch_alter_table('job_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imported_from_posting_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('imported_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('external_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_record', schema=None) as batch_op:
        batch_op.drop_column('external_url')
        batch_op.drop_column('imported_at')
        batch_op.drop_column('imported_from_posting_id')

    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_column('imported')

    # ### end Alembic commands ###
