"""add sector_mappings

Revision ID: 4ebe93768828
Revises: 1bf55d1d5e50
Create Date: 2025-12-12 13:51:30.437676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ebe93768828'
down_revision = '1bf55d1d5e50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sector_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_value', sa.String(length=120), nullable=False),
    sa.Column('canonical_sector', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sector_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sector_mappings_canonical_sector'), ['canonical_sector'], unique=False)
        batch_op.create_index(batch_op.f('ix_sector_mappings_raw_value'), ['raw_value'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('admin_level',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('admin_level',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('sector_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sector_mappings_raw_value'))
        batch_op.drop_index(batch_op.f('ix_sector_mappings_canonical_sector'))

    op.drop_table('sector_mappings')
    # ### end Alembic commands ###
