"""Add day_label

Revision ID: 4ee62f4ef047
Revises: 8d6723795783
Create Date: 2025-11-23 19:17:27.784873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ee62f4ef047'
down_revision = '8d6723795783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cron_run_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day_label', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cron_run_logs', schema=None) as batch_op:
        batch_op.drop_column('day_label')

    # ### end Alembic commands ###
