"""weekly insights ai narratives

Revision ID: 5b3c6d530f23
Revises: d443f76c4d64
Create Date: 2025-12-15 16:30:50.302851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b3c6d530f23'
down_revision = 'd443f76c4d64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('headline', sa.String(length=200), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('ai_generated_at', sa.DateTime(), nullable=True),
    sa.Column('ai_model', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_insights_week_start'), ['week_start'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_insights_week_start'))

    op.drop_table('weekly_insights')
    # ### end Alembic commands ###
