"""Unify models: move to models.py, align JobRecord schema

Revision ID: 64febc2ecb90
Revises: fe716816ab7e
Create Date: 2025-08-28 12:27:51.402289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64febc2ecb90'
down_revision = 'fe716816ab7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analysis_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('filters', sa.Text(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('output_html', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('logo_filename', sa.String(length=200), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('job_record', schema=None) as batch_op:
        batch_op.drop_column('logo_filename')
        batch_op.drop_column('created_at')

    op.drop_table('ai_analysis_log')
    # ### end Alembic commands ###
