"""Add pay_rates and upload_batches tables + indexes

Revision ID: 78b04de80789
Revises: 64febc2ecb90
Create Date: 2025-09-29 19:41:33.063029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78b04de80789'
down_revision = '64febc2ecb90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=True),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('inserted_rows', sa.Integer(), nullable=False),
    sa.Column('updated_rows', sa.Integer(), nullable=False),
    sa.Column('skipped_rows', sa.Integer(), nullable=False),
    sa.Column('errors_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pay_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employer_name', sa.String(length=200), nullable=False),
    sa.Column('organisation', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=False),
    sa.Column('contract_type', sa.String(length=20), nullable=False),
    sa.Column('base_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('weekend_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('night_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bh_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('enhancement_notes', sa.String(length=400), nullable=True),
    sa.Column('mileage_pence', sa.Integer(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('source_url', sa.String(length=400), nullable=True),
    sa.Column('notes', sa.String(length=400), nullable=True),
    sa.Column('region', sa.String(length=80), nullable=False),
    sa.Column('county', sa.String(length=80), nullable=True),
    sa.Column('town_city', sa.String(length=120), nullable=True),
    sa.Column('postcode', sa.String(length=12), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('upload_batch_id', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint('base_rate >= 0', name='chk_payrate_base_rate_nonneg'),
    sa.ForeignKeyConstraint(['upload_batch_id'], ['upload_batches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employer_name', 'role', 'contract_type', 'postcode', 'effective_from', name='uq_payrate_employer_role_contract_postcode_date')
    )
    with op.batch_alter_table('pay_rates', schema=None) as batch_op:
        batch_op.create_index('ix_payrate_latlon', ['lat', 'lon'], unique=False)
        batch_op.create_index('ix_payrate_org', ['organisation'], unique=False)
        batch_op.create_index('ix_payrate_postcode', ['postcode'], unique=False)
        batch_op.create_index('ix_payrate_region', ['region'], unique=False)
        batch_op.create_index('ix_payrate_role', ['role'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pay_rates', schema=None) as batch_op:
        batch_op.drop_index('ix_payrate_role')
        batch_op.drop_index('ix_payrate_region')
        batch_op.drop_index('ix_payrate_postcode')
        batch_op.drop_index('ix_payrate_org')
        batch_op.drop_index('ix_payrate_latlon')

    op.drop_table('pay_rates')
    op.drop_table('upload_batches')
    # ### end Alembic commands ###
