"""Add trigger to cron run log

Revision ID: 8d6723795783
Revises: 
Create Date: 2025-11-23 15:42:33.957015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d6723795783'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cron_run_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trigger', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cron_run_logs', schema=None) as batch_op:
        batch_op.drop_column('trigger')

    # ### end Alembic commands ###
