"""add job_role_sector_overrides

Revision ID: 913137500a6f
Revises: b2ab61169f1c
Create Date: 2025-12-17 17:03:18.795615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913137500a6f'
down_revision = 'b2ab61169f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_role_sector_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_role', sa.String(length=255), nullable=False),
    sa.Column('canonical_sector', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_role_sector_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_role_sector_overrides_canonical_role'), ['canonical_role'], unique=True)
        batch_op.create_index(batch_op.f('ix_job_role_sector_overrides_canonical_sector'), ['canonical_sector'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_role_sector_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_role_sector_overrides_canonical_sector'))
        batch_op.drop_index(batch_op.f('ix_job_role_sector_overrides_canonical_role'))

    op.drop_table('job_role_sector_overrides')
    # ### end Alembic commands ###
