"""Add ons_earnings table

Revision ID: 9c8dc5073015
Revises: b0442f080e0d
Create Date: 2025-12-03 14:34:37.464301

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c8dc5073015'
down_revision = 'b0442f080e0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ons_earnings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('measure_code', sa.String(length=16), nullable=False))
        batch_op.alter_column('geography_code',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=32),
               nullable=False)
        batch_op.alter_column('geography_name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.drop_index('ix_ons_earnings_geography_level')
        batch_op.drop_index('ix_ons_earnings_geography_name')
        batch_op.drop_index('ix_ons_earnings_measure')
        batch_op.drop_index('ix_ons_earnings_period_year')
        batch_op.create_unique_constraint('uq_ons_year_geo_measure', ['year', 'geography_code', 'measure_code'])
        batch_op.drop_column('geography_level')
        batch_op.drop_column('unit')
        batch_op.drop_column('measure')
        batch_op.drop_column('source_table')
        batch_op.drop_column('period_year')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ons_earnings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period_year', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('source_table', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('measure', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('unit', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('geography_level', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
        batch_op.drop_constraint('uq_ons_year_geo_measure', type_='unique')
        batch_op.create_index('ix_ons_earnings_period_year', ['period_year'], unique=False)
        batch_op.create_index('ix_ons_earnings_measure', ['measure'], unique=False)
        batch_op.create_index('ix_ons_earnings_geography_name', ['geography_name'], unique=False)
        batch_op.create_index('ix_ons_earnings_geography_level', ['geography_level'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('value',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('geography_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('geography_code',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=40),
               nullable=True)
        batch_op.drop_column('measure_code')
        batch_op.drop_column('year')

    # ### end Alembic commands ###
