"""Add company_name to JobRecord

Revision ID: 9e45192b6a64
Revises: ac057096a337
Create Date: 2025-04-19 22:50:18.639927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e45192b6a64'
down_revision = 'ac057096a337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_record', schema=None) as batch_op:
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###
