"""Add sector to JobPosting

Revision ID: abadb4e9bd6d
Revises: 4ee62f4ef047
Create Date: 2025-11-27 12:30:00.538485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abadb4e9bd6d'
down_revision = '4ee62f4ef047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sector', sa.String(length=100), nullable=True))
        batch_op.create_index('ix_job_postings_sector', ['sector'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_index('ix_job_postings_sector')
        batch_op.drop_column('sector')

    # ### end Alembic commands ###
