"""add ai suggestion cache to job_role_mappings

Revision ID: af07d537d598
Revises: 3abccda5b897
Create Date: 2025-12-29 15:58:24.576469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af07d537d598'
down_revision = '3abccda5b897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_role_mappings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_canonical_role', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ai_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ai_model', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('ai_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_role_mappings', schema=None) as batch_op:
        batch_op.drop_column('ai_reason')
        batch_op.drop_column('ai_model')
        batch_op.drop_column('ai_score')
        batch_op.drop_column('ai_canonical_role')

    # ### end Alembic commands ###
