"""add ons_earnings

Revision ID: b0442f080e0d
Revises: d9939595263b
Create Date: 2025-12-03 13:06:56.780607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0442f080e0d'
down_revision = 'd9939595263b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ons_earnings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geography_code', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('source_table', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('geography_level',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.alter_column('measure',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.drop_index('ix_ons_geo_period')
        batch_op.create_index(batch_op.f('ix_ons_earnings_geography_code'), ['geography_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_ons_earnings_measure'), ['measure'], unique=False)
        batch_op.create_index(batch_op.f('ix_ons_earnings_period_year'), ['period_year'], unique=False)
        batch_op.drop_column('source')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ons_earnings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_ons_earnings_period_year'))
        batch_op.drop_index(batch_op.f('ix_ons_earnings_measure'))
        batch_op.drop_index(batch_op.f('ix_ons_earnings_geography_code'))
        batch_op.create_index('ix_ons_geo_period', ['geography_level', 'geography_name', 'period_year'], unique=False)
        batch_op.alter_column('measure',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('geography_level',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('unit')
        batch_op.drop_column('source_table')
        batch_op.drop_column('geography_code')

    # ### end Alembic commands ###
