"""Add AI fields to weekly market changes

Revision ID: b2ab61169f1c
Revises: 5b3c6d530f23
Create Date: 2025-12-15 16:45:54.772338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2ab61169f1c'
down_revision = '5b3c6d530f23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_market_changes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_narrative', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ai_driver_tags', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ai_model', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('ai_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_market_changes', schema=None) as batch_op:
        batch_op.drop_column('ai_updated_at')
        batch_op.drop_column('ai_model')
        batch_op.drop_column('ai_driver_tags')
        batch_op.drop_column('ai_narrative')

    # ### end Alembic commands ###
