"""Add last_login_at to user

Revision ID: b9512d95a086
Revises: af07d537d598
Create Date: 2025-12-31 09:36:24.689255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9512d95a086'
down_revision = 'af07d537d598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_last_login_at'), ['last_login_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_last_login_at'))
        batch_op.drop_column('last_login_at')

    # ### end Alembic commands ###
