"""add run_stats to cron run log

Revision ID: c504653c8669
Revises: 4ebe93768828
Create Date: 2025-12-14 18:37:30.208898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c504653c8669'
down_revision = '4ebe93768828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cron_run_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('run_stats', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cron_run_logs', schema=None) as batch_op:
        batch_op.drop_column('run_stats')

    # ### end Alembic commands ###
