"""add job_summary_daily

Revision ID: d3adedd92839
Revises: 1678b54efd38
Create Date: 2025-12-02 17:05:06.413035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3adedd92839'
down_revision = '1678b54efd38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_summary_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('county', sa.String(length=50), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('job_role_group', sa.String(length=120), nullable=True),
    sa.Column('adverts_count', sa.Integer(), nullable=True),
    sa.Column('median_pay_rate', sa.Float(), nullable=True),
    sa.Column('p25_pay_rate', sa.Float(), nullable=True),
    sa.Column('p75_pay_rate', sa.Float(), nullable=True),
    sa.Column('min_pay_rate', sa.Float(), nullable=True),
    sa.Column('max_pay_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_summary_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_summary_daily_county'), ['county'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_summary_daily_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_summary_daily_job_role_group'), ['job_role_group'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_summary_daily_sector'), ['sector'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_summary_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_summary_daily_sector'))
        batch_op.drop_index(batch_op.f('ix_job_summary_daily_job_role_group'))
        batch_op.drop_index(batch_op.f('ix_job_summary_daily_date'))
        batch_op.drop_index(batch_op.f('ix_job_summary_daily_county'))

    op.drop_table('job_summary_daily')
    # ### end Alembic commands ###
