"""Add weekly market changes

Revision ID: d443f76c4d64
Revises: d8ffd25fc430
Create Date: 2025-12-15 15:44:49.859821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd443f76c4d64'
down_revision = 'd8ffd25fc430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_market_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('metric_type', sa.String(length=30), nullable=False),
    sa.Column('job_role', sa.String(length=120), nullable=True),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('value_previous', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('value_current', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('delta_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('delta_percent', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.Column('confidence_level', sa.SmallInteger(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_market_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_market_changes_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_market_changes_job_role'), ['job_role'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_market_changes_location'), ['location'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_market_changes_metric_type'), ['metric_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_market_changes_sector'), ['sector'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_market_changes_week_end'), ['week_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_market_changes_week_start'), ['week_start'], unique=False)
        batch_op.create_index('ix_wmc_week_metric', ['week_start', 'metric_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_market_changes', schema=None) as batch_op:
        batch_op.drop_index('ix_wmc_week_metric')
        batch_op.drop_index(batch_op.f('ix_weekly_market_changes_week_start'))
        batch_op.drop_index(batch_op.f('ix_weekly_market_changes_week_end'))
        batch_op.drop_index(batch_op.f('ix_weekly_market_changes_sector'))
        batch_op.drop_index(batch_op.f('ix_weekly_market_changes_metric_type'))
        batch_op.drop_index(batch_op.f('ix_weekly_market_changes_location'))
        batch_op.drop_index(batch_op.f('ix_weekly_market_changes_job_role'))
        batch_op.drop_index(batch_op.f('ix_weekly_market_changes_direction'))

    op.drop_table('weekly_market_changes')
    # ### end Alembic commands ###
