"""add ons earnings

Revision ID: d9939595263b
Revises: d3adedd92839
Create Date: 2025-12-03 12:57:57.127571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9939595263b'
down_revision = 'd3adedd92839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ons_earnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geography_level', sa.String(length=20), nullable=False),
    sa.Column('geography_name', sa.String(length=120), nullable=False),
    sa.Column('period_year', sa.Integer(), nullable=False),
    sa.Column('measure', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ons_earnings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ons_earnings_geography_level'), ['geography_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_ons_earnings_geography_name'), ['geography_name'], unique=False)
        batch_op.create_index('ix_ons_geo_period', ['geography_level', 'geography_name', 'period_year'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ons_earnings', schema=None) as batch_op:
        batch_op.drop_index('ix_ons_geo_period')
        batch_op.drop_index(batch_op.f('ix_ons_earnings_geography_name'))
        batch_op.drop_index(batch_op.f('ix_ons_earnings_geography_level'))

    op.drop_table('ons_earnings')
    # ### end Alembic commands ###
