"""Add JobPosting model

Revision ID: edeada651488
Revises: 78b04de80789
Create Date: 2025-11-18 19:04:37.369979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edeada651488'
down_revision = '78b04de80789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('location_text', sa.String(length=255), nullable=True),
    sa.Column('postcode', sa.String(length=20), nullable=True),
    sa.Column('min_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rate_type', sa.String(length=50), nullable=True),
    sa.Column('contract_type', sa.String(length=50), nullable=True),
    sa.Column('source_site', sa.String(length=100), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.create_index('ix_job_postings_source_ext', ['source_site', 'external_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_index('ix_job_postings_source_ext')

    op.drop_table('job_postings')
    # ### end Alembic commands ###
