"""Add AIAnalysisLog table

Revision ID: fe716816ab7e
Revises: db47237b45a9
Create Date: 2025-08-28 11:12:43.098628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe716816ab7e'
down_revision = 'db47237b45a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_record', schema=None) as batch_op:
        batch_op.drop_index('ix_jobrecord_filters')
        batch_op.create_index(batch_op.f('ix_job_record_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_record_county'), ['county'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_record_imported_month'), ['imported_month'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_record_imported_year'), ['imported_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_record_job_role'), ['job_role'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_record_sector'), ['sector'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    with op.batch_alter_table('job_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_record_sector'))
        batch_op.drop_index(batch_op.f('ix_job_record_job_role'))
        batch_op.drop_index(batch_op.f('ix_job_record_imported_year'))
        batch_op.drop_index(batch_op.f('ix_job_record_imported_month'))
        batch_op.drop_index(batch_op.f('ix_job_record_county'))
        batch_op.drop_index(batch_op.f('ix_job_record_company_id'))
        batch_op.create_index('ix_jobrecord_filters', ['sector', 'job_role', 'county', 'imported_year', 'imported_month'], unique=False)

    # ### end Alembic commands ###
